### ISSUE TITLE
Bug: Dragging an app causes exception [4-8h]

### ISSUE THREAD

**Issue by literacyapp** [literacyapp-org/android_packages_apps_Trebuchet_Gradle#7]
```
01-29 17:29:31.173  4236  4249 E DatabaseUtils: Writing exception to parcel
01-29 17:29:31.173  4236  4249 E DatabaseUtils: java.lang.SecurityException: Permission Denial: writing com.android.launcher3.LauncherProvider uri content://com.android.launcher3.settings/favorites/20 from pid=8468, uid=10102 requires com.android.launcher3.permission.WRITE_SETTINGS, or grantUriPermission()
01-29 17:29:31.173  4236  4249 E DatabaseUtils: 	at android.content.ContentProvider.enforceWritePermissionInner(ContentProvider.java:679)
01-29 17:29:31.173  4236  4249 E DatabaseUtils: 	at android.content.ContentProvider$Transport.enforceWritePermission(ContentProvider.java:494)
01-29 17:29:31.173  4236  4249 E DatabaseUtils: 	at android.content.ContentProvider$Transport.update(ContentProvider.java:350)
01-29 17:29:31.173  4236  4249 E DatabaseUtils: 	at android.content.ContentProviderNative.onTransact(ContentProviderNative.java:222)
01-29 17:29:31.173  4236  4249 E DatabaseUtils: 	at android.os.Binder.execTransact(Binder.java:453)
01-29 17:29:31.173  8468  8489 E AndroidRuntime: FATAL EXCEPTION: launcher-loader
01-29 17:29:31.173  8468  8489 E AndroidRuntime: Process: com.android.launcher3, PID: 8468
01-29 17:29:31.173  8468  8489 E AndroidRuntime: Theme: themes:{}
01-29 17:29:31.173  8468  8489 E AndroidRuntime: java.lang.SecurityException: Permission Denial: writing com.android.launcher3.LauncherProvider uri content://com.android.launcher3.settings/favorites/20 from pid=8468, uid=10102 requires com.android.launcher3.permission.WRITE_SETTINGS, or grantUriPermission()
01-29 17:29:31.173  8468  8489 E AndroidRuntime: 	at android.os.Parcel.readException(Parcel.java:1620)
01-29 17:29:31.173  8468  8489 E AndroidRuntime: 	at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:183)
01-29 17:29:31.173  8468  8489 E AndroidRuntime: 	at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:135)
01-29 17:29:31.173  8468  8489 E AndroidRuntime: 	at android.content.ContentProviderProxy.update(ContentProviderNative.java:568)
01-29 17:29:31.173  8468  8489 E AndroidRuntime: 	at android.content.ContentResolver.update(ContentResolver.java:1367)
01-29 17:29:31.173  8468  8489 E AndroidRuntime: 	at com.android.launcher3.LauncherModel$7.run(LauncherModel.java:742)
01-29 17:29:31.173  8468  8489 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:739)
01-29 17:29:31.173  8468  8489 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:95)
01-29 17:29:31.173  8468  8489 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:148)
01-29 17:29:31.173  8468  8489 E AndroidRuntime: 	at android.os.HandlerThread.run(HandlerThread.java:61)
01-29 17:29:31.174   522   666 W ActivityManager:   Force finishing activity com.android.launcher3/.Launcher
01-29 17:29:31.176   522   666 I ActivityManager: Clearing package preferred activities from com.android.launcher3
```

**Comment by jogrimst** [comment]
This error is probably related to #2

**Comment by bojanvu23** [comment]
@jogrimst 

Can we close this?

**Comment by bojanvu23** [comment]
This is fixed, closing ticket.
